### ISSUE TITLE
Why not use gumbel in multidiscrete?

### ISSUE THREAD

**Issue by mateuspontesm** [JohannesAck/tf2multiagentrl#2]
In your code you only check for Discrete in the act_type and only uses gumbel_softmax in that case. There's a reason to not use it in the multidiscrete case or is it just a mistake?

**Comment by JohannesAck** [comment]
Sorry about the delay. I didn't test on any multidiscrete environments, as the multiagent-particle-envs by openai specify their action spaces as discrete.

Their actionspaces in fact are not discrete, but the gumbel in my implementation replicates how they treat the actionspaces in the original MADDPG implementation by openai.

If you actually have a real multi-discrete environment, I think the current implementation of the gumbel-softmax might not handle it correctly.

**Comment by mateuspontesm** [comment]
Actually, they use an old version of the MultiDiscrete:
https://github.com/openai/multiagent-particle-envs/blob/69ee7f85811c77ee651722bc3c332677b2195da1/multiagent/environment.py#L59

```
if len(total_action_space) > 1:
    # all action spaces are discrete, so simplify to MultiDiscrete action space
    if all([isinstance(act_space, spaces.Discrete) for act_space in total_action_space]):
        act_space = MultiDiscrete([[0, act_space.n - 1] for act_space in total_action_space])
     else:
         act_space = spaces.Tuple(total_action_space)
     self.action_space.append(act_space)
```
I think the simple_crypto is one of those cases. 
Anyway, I liked your implementation, but I made my own because I wasn't sure of the multi-discrete. 

Any reason for why you didn't use the RelaxedOneHotCategorical  and implemented your own gumbel-softmax?

**Comment by JohannesAck** [comment]
Oh you're right, I must have missed that in their code, my bad. I'm not exactly sure how that impacts comparability, but I'm still pretty sure that the gumbel-softmax was used when testing on the environment. I'll have to test it when I find time.

>Any reason for why you didn't use the RelaxedOneHotCategorical and implemented your own gumbel-softmax?

I think back when I first implemented it it was causing issues with tf.function's graph generation. However that was one and a half years ago, so maybe it would work fine now.
