### ISSUE TITLE
Unknown Space Type on Communication Based Scenarios

### ISSUE THREAD

**Issue by ongr1996** [JohannesAck/tf2multiagentrl#4]
First of all, I appreciate your TF2 implementation of multi-agent particle envs and I tried utilizing it in a conda env. I wanted to create my own scenario similar to that of the simple_reference scenario but I came across space type errors whenever the agents could send communication signals and was also capable of moving (meaning speaker_listener worked, but reference and world_comm gave me space type errors). I noticed upon silencing the agents in these scenarios, the scenarios would run; so I presume it had something to do with a conflict of action and observation spaces.

Errors from *policy*Agent, *policy*, and util: 
space_to_shape

Any suggestions on what I could do to fix this and/or where I could get a better understanding on spaces and why this is occurring would be greatly appreciated.

**Comment by JohnsonJiang1996** [comment]
I came across the same issues. Currently working on it.

**Comment by JohnsonJiang1996** [comment]
Not sure whether you can still see this. But I think I fixed it. This error came from the space to shape function of util.py, the author originally only added the box and discrete types, but in fact, we also used the Discrete and Tuple types in the action, so just change this function.
`from gym.spaces import Tuple
from tf2marl.multiagent.multi_discrete import MultiDiscrete

def space_to_shape(space):
    """
    Takes a gym.space and returns its shape
    """
    if isinstance(space, Box):
        return space.shape
    elif isinstance(space, Discrete):
        return [space.n]
    elif isinstance(space, MultiDiscrete):
        return [sum(space.high - space.low + 1)]
    elif isinstance(space, Tuple):
        # Assuming each element in the tuple is a Discrete space
        # Modify this logic if your Tuple spaces have different structures
        return [sum(element.n for element in space.spaces)]
    else:
        raise RuntimeError(f"Unknown space type: {type(space)}. Can't return shape.")
`

**Comment by JohannesAck** [comment]
Hi @JohnsonJiang1996 ,
thanks a lot for providing the fix!
If you'd like to open a pull-request I would be happy to merge it!

**Comment by JohnsonJiang1996** [comment]
> Hi @JohnsonJiang1996 , thanks a lot for providing the fix! If you'd like to open a pull-request I would be happy to merge it!

Thanks! I just opened a pull-request.

**Comment by JohannesAck** [comment]
This has been solved by @JohnsonJiang1996 's pull request in #9, again thanks a lot!
I'll close this for now, let me know if there are any other issues!
