### ISSUE TITLE
Unknow how to test the results

### ISSUE THREAD

**Issue by chenga02** [JohannesAck/tf2multiagentrl#7]
Could you please tell me how to test the results after training?

**Comment by JohannesAck** [comment]
Hi,
Thanks for using the repository!
You can load previous checkpoints using this configuration parameter:
https://github.com/JohannesAck/tf2multiagentrl/blob/8b63174b5d314cbf29a7ff2414d5999a0224c03d/train.py#L37-L38

Hope this helps!

Best,
Johannes
