### ISSUE TITLE
PER MADDPG rewards are worse than MADDPG. Why is that?

### ISSUE THREAD

**Issue by kailashg26** [JohannesAck/tf2multiagentrl#8]
Hello,

Thanks for the tf2.x implementation of MADDPG. Appreciate your effort.

I was wondering if you know the reason why does PER MADDPG perform worse than MADDPG in terms of the rewards. I tested using simple tag and simple spread and observed no improvement in rewards, but rather the rewards are degraded.

It would be great if you let me know any insights you have on this issue.

Thanks,

Kailash

**Comment by JohannesAck** [comment]
Hi Kailash,

Yes I observed the same effect when trying to use prioritized experience replay, it usually would just degrade performance.

Honestly, I never got it to work and it's been about four years since I wrote this code so I don't have any particular insights to share.
If I had to work on it again I would probably try to construct a toy example where PER should show large benefits, and test it first with a single agent and then multiple ones.

Feel free to post in this issue or message me if you want to chat more about this!

Best,
Johannes

**Comment by kailashg26** [comment]
Hey, thanks for the reply. I'm wondering what might be the reason for that. Do you know any multiagent prioritized experience replay papers which show improvement using PER? I know MAC-PO from AAMAS23 Shows that for QMIX, but they use multiple terms with a bellman error.

Also, is there any published paper with MADDPG-PER implemented and tested? By the way, is the trend the same for matd3, masac when applied with PER?

**Comment by JohannesAck** [comment]
> Do you know any multiagent prioritized experience replay papers which show improvement using PER?

I do not know any such papers, but I haven't been following the Multi-Agent literature very closely recently.

> MAC-PO from AAMAS23 Shows that for QMIX, but they use multiple terms with a bellman error.

From skimming their paper, Fig. 2a) seems to show a very small gain by using their MAC-PO method compared to QMix without any PER-like scheme on a particle-env task. MAC-PO works significantly better than PER in the starcraft setting (Fig. 1), so assuming this is also true in the particle-env tasks, this seems consistent with our findings of PER not working well with MADDPG.

> By the way, is the trend the same for matd3, masac when applied with PER?

For MATD3 the trend is the same, if I recall correctly. I don't think i tried it with SAC.

I would also speculate that the lack of benefit from using PER might stems from the particle-env tasks simply being to easy, but that's really pure speculation.

**Comment by JohannesAck** [comment]
I will close this for now, as it's not an issue of the code, rather a drawback of one of the approaches.

**Comment by JohannesAck** [comment]
@kailashg26 
If you're still working on this, I saw a poster at NeurIPS that discussed problems of PER with high stochasticity, that I believe is related to the issue of PER not working in Multi-Agent RL; https://arxiv.org/abs/2208.10483
